# source 'https://rubygems.org'
source 'http://production.s3.rubygems.org'
ruby "2.1.5"

gem 'active_model_serializers'
gem 'pry'
gem 'pg'
gem 'devise'
gem 'omniauth-twitter'
gem 'uuidtools'
gem 'figaro', '1.0'


group :development, :test do
  # gem 'sqlite3'
  gem 'spring'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'jsonpath'
end

group :test do
  gem 'faker'
  gem 'database_cleaner'
end

gem 'rails_12factor', group: :production

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.8'
gem 'sdoc', '~> 0.4.0',          group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

