# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dcca68881c7b7ef73d36bcca7586c9a66ffab6068fd2f30357222d4ec6890034bd900978cd4164fbeccf0abe333fe4abb2ed667748f1932ae8490f36ab48311

test:
  secret_key_base: d41cf8926fa48a014bf7d635345bbf5183fc6c0e7e7ca774b76969f7485cb14d13b047669d84610d522ea9896aa216f9ba5ac069e64b1e81d5f097596d90428a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
